apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fcg-catalog-secrets
  namespace: fcg
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: 8ec28240-b8eb-45b2-847d-b477002860f3
    tenantId: 6c5cda55-11ba-4255-a1b6-f408421a47be
    keyvaultName: kv-fcg-prod

    objects: |
      array:
        - |
          objectName: Catalog-ConnectionString
          objectType: secret
        - |
          objectName: Redis-ConnectionString
          objectType: secret
        - |
          objectName: MongoDB-ConnectionString
          objectType: secret
        - |
          objectName: AzureSearch--Endpoint
          objectType: secret
        - |
          objectName: AzureSearch--ApiKey
          objectType: secret

  secretObjects:
    - secretName: fcg-catalog-secret
      type: Opaque
      data:
        - objectName: Catalog-ConnectionString
          key: ConnectionStrings__Default

        - objectName: Redis-ConnectionString
          key: Redis__ConnectionString

        - objectName: MongoDB-ConnectionString
          key: MongoDB__ConnectionString

        - objectName: AzureSearch--Endpoint
          key: AzureSearch__Endpoint

        - objectName: AzureSearch--ApiKey
          key: AzureSearch__ApiKey
