apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: fcg-catalog-secrets
  namespace: fcg

spec:
  provider: azure

  secretObjects:
    - secretName: fcg-catalog-secret
      type: Opaque

      data:
        - objectName: Redis--ConnectionString
          key: Redis__ConnectionString

        - objectName: MongoDB--ConnectionString
          key: MongoDB__ConnectionString

        - objectName: AzureSearch--Endpoint
          key: AzureSearch__Endpoint

        - objectName: AzureSearch--ApiKey
          key: AzureSearch__ApiKey

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "<WORKLOAD_IDENTITY_CLIENT_ID>"
    keyvaultName: "<KEYVAULT_NAME>"
    tenantId: "<TENANT_ID>"

    objects: |
      array:
        - |
          objectName: Redis--ConnectionString
          objectType: secret
        - |
          objectName: MongoDB--ConnectionString
          objectType: secret
        - |
          objectName: AzureSearch--Endpoint
          objectType: secret
        - |
          objectName: AzureSearch--ApiKey
          objectType: secret
